language: android
jdk: oraclejdk8
dist: trusty
sudo: true
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - android-26


before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git config --global user.name "Travis CI"
  - git config --global user.email "tcisagebio@sagebase.org"

install:
  - gem install bundler
  - bundle install

stages:
  - test
  - name: check
    if: branch !~ /^stable-.*$/
  - name: deploy
    if: branch =~ /^stable-.*$/

jobs:
  include:
    - stage: test
      script: bundle exec fastlane test
    - stage: check
      script: bundle exec fastlane assemble
    - stage: deploy
      script: ./travis/deploy.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache